import { worksArrayType } from "@/types/worksType";

const worksArray : worksArrayType = {
    ArrayList : [
        {
        id : "cosmo",
        name : "コスモカフェ",
        type : "すべて",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/cosmo.jpg",
        text : `Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。`,
        imageColor : "#efefef",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/cosmo-cafe/",
        },
        {
        id : "free",
        name : "freeme",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30 ,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/freeme.jpg",
        text : `1年生の夏休みの時期に制作したYahoo!Japan主催の学生ハッカソン"Hack U"にて制作したものです`,
        imageColor : "#efefef",
        url : ""
        },
        {
        id : "non",
        name : "NONST",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/nonst.jpg",
        text : '1年生の夏休み時期に制作した学内短期制作にて制作したものです、愚痴を聞く人と話す人のマッチングアプリサービスです。',
        imageColor : "#efefef",
        url : "",
        },
        {
        id : "gole",
        name : "GolePort",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/goleport.jpg",
        text : 'Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。',
        imageColor : "#efefef",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/goleport/LP/",
        },
        {
        id : "umi",
        name : "うみとこころとぼく",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/umito.jpg",
        text : "textArray",
        imageColor : "#B6D8E1",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/umitokokorotoboku_LP/",
    },
    {
        id : "fago",
        name : "fagory",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/maturi.jpg",
        text : "textArray",
        imageColor : "#efefef",
        url : "",
        },
        {
        id : "maturi",
        name : "まつりる",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/maturi.jpg",
        text : "textArray",
        imageColor : "#efefef",
        url : "",
        },
        {
        id : "osake",
        name : "おさけたて",
        type : "engeneer",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/osake.jpg",
        text : "textArray",
        imageColor : "#efefef" , 
        url : "" , 
        },
    ]
};

export default worksArray