import { worksArrayType } from "@/types/worksType";

const worksArray : worksArrayType = {
    ArrayList : [
        {
        id : "cosmo",
        name : "コスモカフェ",
        type : "すべて",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "webサイト",
        img : "./img/cosmo.jpg",
        text : `Webを学んで初めて企画から実装まで1人で行った制作物です。宇宙をコンセプトにしたカフェのWebサイトです。`,
        imageColor : "#4F6186",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/cosmo-cafe/",
        },
        // {
        // id : "free",
        // name : "freeme",
        // type : "エンジニア",
        // langage : ['html',"css"],
        // nop : "チーム制作",
        // time : 30 ,
        // sch : "1年生前期",
        // main : "アプリ",
        // img : "./img/freeme.jpg",
        // text : `1年生の夏休みの時期に制作したYahoo!Japan主催の学生ハッカソン"Hack U"にて制作したものです`,
        // imageColor : "#4ECCC3",
        // url : ""
        // },
        {
        id : "non",
        name : "NONST",
        type : "エンジニア",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 30,
        sch : "1年生前期",
        main : "LP",
        img : "/img/nonst.jpg",
        text : '1年生の夏休み時期に制作した学内短期制作にて制作したものです、愚痴を聞く人と話す人のマッチングアプリサービスです。',
        imageColor : "#0A345A",
        url : "https://nonst-lp.vercel.app/",
        },
        {
        id : "gole",
        name : "GolePort",
        type : "すべて",
        langage : ['html',"css"],
        nop : "個人制作",
        time : 40,
        sch : "1年生後期",
        main : "webサイト",
        img : "./img/goleport.jpg",
        text : '2回目の個人制作でのLPです。学生同士が組んだプロジェクトを企業や一般の方が後押しできるサービスです。',
        imageColor : "#5B5242",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/goleport/LP/",
        },
        {
        id : "umi",
        name : "うみとこころとぼく",
        type : "エンジニア",
        langage : ['html',"css"],
        nop : "チーム制作",
        time : 30,
        sch : "1年生後期",
        main : "LP",
        img : "./img/umito.jpg",
        text : "SNS疲れを焦点を当てたGoogleChromeの拡張機能です。着せ替えやメッセージ交換が楽しめます。",
        imageColor : "#709EAA",
        url : "https://click.ecc.ac.jp/ecc/ksimokawa/umitokokorotoboku_LP/",
        },
        // {
        // id : "fago",
        // name : "fagory",
        // type : "すべて",
        // langage : ['html',"css"],
        // nop : "個人制作",
        // time : 30,
        // sch : "2年生前期",
        // main : "アプリ",
        // img : "./img/maturi.jpg",
        // text : "textArray",
        // imageColor : "#efefef",
        // url : "",
        // },
        {
        id : "maturi",
        name : "まつりる",
        type : "デザイン",
        langage : ['html',"css"],
        nop : "チーム制作",
        time : 30,
        sch : "2年生前期",
        main : "アプリ",
        img : "./img/maturi.jpg",
        text : "祭りを開いている自治体と出店を開きたい人をマッチングさせるサービスです。「お手軽」を大切にしました。",
        imageColor : "#8D0C18",
        url : "https://www.figma.com/proto/P4SxOKWuwMavdYKvjd7J1k/Untitled?node-id=2%3A8&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A8&show-proto-sidebar=1",
        },
        {
        id : "osake",
        name : "おさけたて",
        type : "デザイン",
        langage : ['html',"css"],
        nop : "チーム制作",
        time : 30,
        sch : "1年生前期",
        main : "LP",
        img : "./img/osake.jpg",
        text : "お酒初心者の人の恐怖心を無くしてお酒の楽しみ方を教えるサービスです。店舗に加盟していただくサービスになります。",
        imageColor : "#BD6306" , 
        url : "https://osaketate-lp.vercel.app/" , 
        },
    ]
};

export default worksArray